### ISSUE TITLE
Option -f is broken

### ISSUE THREAD

**Issue by nponeccop** [johnlcf/Stana#5]
```
$ python2 ./strace_analyser -f -e StatFileIO foo.trace
Traceback (most recent call last):
  File "./strace_analyser", line 223, in <module>
    main()                                                             
  File "./strace_analyser", line 141, in main
    straceOptions["haveTime"] = "t" * options.withtime
TypeError: can't multiply sequence by non-int of type 'NoneType'
```

**Comment by nponeccop** [comment]
Yes. See #6 for a sample line
